### ISSUE TITLE
Are you Japaness? Can you make a English README.md?

### ISSUE THREAD

**Issue by loveboom** [yuki540net/toa#1]

**Comment by yui540** [comment]
すみません。私は英語ができません。

**Comment by hykw** [comment]
Why don't you read thru Google Translate? As far as I see,  translated correctly, though I only glanced over.

https://translate.googleusercontent.com/translate_c?act=url&depth=1&hl=en&ie=UTF8&prev=_t&rurl=translate.google.com&sl=auto&sp=nmt4&tl=en&u=https://github.com/yuki540net/toa&usg=ALkJrhj03rlS2ECUyK6TCMP8bhvGfN7Y4w

**Comment by loveboom** [comment]
君は格好がいい
君の言うことはみな正しい。
